### PR TITLE
Martin py3 dracut

### PR DESCRIPTION
**Pull request by bcl**
Also includes the parse-kickstart test ported to py3 as well as an updated makebumpver

### CODE REVIEW

**Comment by vpodzime** [comment]
Other than the minor comments above these look good to me. Thanks!

**Comment by M4rtinK** [comment]
Thanks! Also looks good to me. :)

**Comment by vpodzime** [comment]
The new version looks perfect. Thanks!

**Comment by M4rtinK** [comment]
Applied locally, thanks! :)

**Pull request closed without merging**
