### PR TITLE
cockpit: add simple example of using the dbus API for reading and writing properties

### PR DESCRIPTION
**Pull request by KKoukiou**
* deep-equal new dependency was introduce as it's needed by new newly
imported pkg/lib/hooks
* react/jsx-closing-bracket-location was turnedoff because it's gives
unfixable warnings - cockpit repo turns it off as well

### CODE REVIEW

**Comment by KKoukiou** [comment]
@M4rtinK please ignore till till tomorow - somehow I broke it last minute.

**Comment by KKoukiou** [comment]
@M4rtinK no need to review the react parts that you 're not familiar with. Mostly test it interactively but of course js review welcome. 

You should now see something like this without the button. 
anaconda-dbus

**Review by M4rtinK — APPROVED** [review]
Looks good to me as far as I can tell. :)

I'm sure that over time I will be able to absorb more of this JS stuff. :)

**Comment by M4rtinK** [comment]
> @M4rtinK no need to review the react parts that you 're not familiar with. Mostly test it interactively but of course js review welcome.
> 
> You should now see something like this without the button.

Wooo! Really nice! :-D

**Pull request merged**
