### PR TITLE
Add target for fetching cockpit's testing library in anaconda-webui Makefile

### PR DESCRIPTION
**Pull request by KKoukiou**
Also add the first test file which can be now invoked manually and run
against a machine running the anaconda new web ui.

This test can be run like this:

1. Run a VM with this anaconda branch
2. Login to the VM and run a new cockpit-ws instance:
   /usr/libexec/cockpit-ws --no-tls --port 9090 --local-session=cockpit-bridge
   This will allow us to connect from the browser of the machine running
   the test to the VM
3. Find the IP adress of the VM running anaconda,
   ex: sudo virsh domifaddr cockpit-new-ui-VM
4. Run the test:
   TEST_SHOW_BROWSER=true TEST_RUNNING_INSTALLER=true ./test/check-basic -st --machine 192.168.122.124
   Replace the IP address passed to --machine CLI option.
   TEST_SHOW_BROWSER=true is not needed, it just spawns a browser
   for interactive testing and makes debugging easy. If not passed, the
   test will run in headless mode.

Until https://github.com/cockpit-project/bots/pull/2717 is merged one
needs to cherry-pick this commit into the bots checkout for testing to
work.

### CODE REVIEW

**Comment by KKoukiou** [comment]
@jkonecny12 @M4rtinK I would like to add this check-basic file in the pep8 and/or pylint existing checks. I did not figure out how to add it yet so any hints welcome.

**Review by M4rtinK — APPROVED** [review]
Had to figure a few things on my end but made it work and it runs nicely & quite quickly! Thanks a lot - looks good to me! :)

**Comment by jkonecny12** [comment]
Great test, thanks for this!

**Comment by jkonecny12** [comment]
> 

Easiest way is to run it in the script or better add a new script for that:

Here is list of scripts:
https://github.com/rhinstaller/anaconda/blob/master/tests/Makefile.am#L46

Here is pylint script directly:
https://github.com/rhinstaller/anaconda/blob/master/tests/pylint/runpylint.py

**Pull request merged**
